name: Java CI with Maven
run-name: ${{ github.actor }} has started workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
   ## Build and execute every test
    - name: Executing Tests
      run: mvn test --file appzara/pom.xml

    ## Generate Test Report Summary
    - name: Test Report
      uses: dorny/test-reporter@v1.6.0
      if: always()
      with:
        name: Test Reporter Summary
        path: appzara/bootstrap/target/surefire-reports/*.xml
        reporter: java-junit