name: Java CI with Maven
run-name: ${{ github.actor }} has started workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build and test with Maven
      run: mvn -B package --file appzara/pom.xml

      ## Build and execute every test
    - name: Executing Tests
      run: mvn test --file appzara/pom.xml

    ## Generate Test Report Summary
    - name: Test Report
      uses: dorny/test-reporter@v1.6.0
      if: always()
      with:
        name: Test Reporter Summary
        path: surefire-reports/*.xml
        reporter: appzara/bootstrap/target/surefire-reports/*.xml,

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
